id: AEADF4660
title: Prayer to the Lineage of the Great Chetsün’s Profound Essence of Vimala
type: translation
pechas:
- IC1A57994
- IBBDD8B4D
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:01:06.469739
  last_modified_at: 2023-01-04 12:01:06.469751
  collections:
  - Jamgön Kongtrul Lodrö Thaye Series
  - Works of Tibetan Masters
alignment_to_base:
  IC1A57994/DD0B: 01C8
  IBBDD8B4D/B69A: 01C8
